# Reference: https://artifacthub.io/packages/helm/jenkinsci/jenkins/5.8.124

# persistence:
#   mounts:
#     - name: jenkins-home
#       mountPath: /tmp/backup

serviceAccount:
  create: true

controller:
  image:
    tag: 2.504.3-jdk21

  # JCasC:
  #   configScripts:
  #     agents: |
  #       jenkins:
  #         nodes:
  #           - permanent:
  #               name: "General"
  #               remoteFS: "/home/jenkins/agent-general"
  #               numExecutors: 1
  #               launcher:
  #                 inbound:
  #                   workDirSettings:
  #                     disabled: false
  #                     workDirPath: "/home/jenkins/agent-general"
  #                     internalDir: "remoting"
  admin:
    existingSecret: "jenkins-admin-creds"
    userKey: jenkins-admin-user
    passwordKey: jenkins-admin-password
  ## BACKUP JENKINS
  # jenkinsHome: "/tmp/backup"
  # containerEnv:
  #   - name: JENKINS_HOME
  #     value: "/tmp/backup"

  additionalPlugins:
    - uno-choice:2.8.8
    - thinBackup:2.1.3
    - aws-credentials:254.v978a_5e206a_d7
    - azure-credentials:395.vb_a_9203343ef5
    - rebuild:338.va_0a_b_50e29397
    - ansicolor:1.0.6
    - audit-trail:436.vc0d1e79fc5a_3
    - audit-log:1.3
    - custom-folder-icon:2.21
    - pipeline-stage-view:2.37

  resources:
    requests:
      cpu: "200m"
      memory: "500Mi"
    limits:
      cpu: "500m"
      memory: "1000Mi"

  ingress:
    enabled: false
    labels: {}
    annotations:
      argocd.argoproj.io/ignore-healthcheck: "true"
    hostName: jenkins.khangtictoc.io
    ingressClassName: nginx

  prometheus:
    enabled: false
    scrapeInterval: 30s
    scrapeEndpoint: /prometheus

agent:
  enabled: true
  jenkinsUrl: khangtictoc.jenkins.io
