apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runners
  namespace: argocd-apps
spec:
  project: default
  sources:
    - repoURL: oci://ghcr.io/actions/actions-runner-controller-charts
      chart: ha-runner-scale-set
      targetRevision: 0.14.2
      helm:
        valueFiles:
          - $values/argocd_values/arc-runners/values.yaml
    - repoURL: "https://github.com/khangtictoc/ArgoCD-Apps.git"
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-runners
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
