# Reference: https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set/values.yaml

githubConfigSecret: gh-action-runner-connector-creds
githubConfigUrl: https://github.com/khangtictoc/All-In-One-Devops-Pipelines

controllerServiceAccount:
  namespace: arc-system
  name: arc-gha-rs-controller
