# Reference: https://github.com/khangtictoc/jenkins-inbound-agent-helm-chart

image:
  repository: "darkhero101/jenkins-inbound-agent-common"
  tag: "0.10.0"

imagePullSecrets:
  - name: jenkins-agent-dockerhub-connector-creds

agent:
  name: "General"
  workDir: "/home/jenkins/agent-general"
  jenkinsTunnel: "jenkins-agent.jenkins.svc.cluster.local:50000"
  jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
  jenkinsSecretName: "jenkins-agent-master-connector-creds"
  jenkinsSecretKey: JENKINS_AGENT_SECRET_GENERAL

  kaniko:
    enabled: true
    dockerSecretName: jenkins-agent-dockerhub-connector-creds
    sharedVolumes:
      - name: workspace
        mountPath: /home/jenkins/agent-general

livenessProbe: {}
readinessProbe: {}
